/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CompanySignInBadRequestResponse,
  CompanySignInInput,
  CompanySignInOkResponse,
} from "../models/index";
import {
  CompanySignInBadRequestResponseFromJSON,
  CompanySignInBadRequestResponseToJSON,
  CompanySignInInputFromJSON,
  CompanySignInInputToJSON,
  CompanySignInOkResponseFromJSON,
  CompanySignInOkResponseToJSON,
} from "../models/index";

export interface PostCompanySignInRequest {
  companySignInInput: CompanySignInInput;
}

/**
 *
 */
export class CompaniesApi extends runtime.BaseAPI {
  /**
   * Company Sign In
   */
  async postCompanySignInRaw(
    requestParameters: PostCompanySignInRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompanySignInOkResponse>> {
    if (requestParameters["companySignInInput"] == null) {
      throw new runtime.RequiredError(
        "companySignInInput",
        'Required parameter "companySignInInput" was null or undefined when calling postCompanySignIn().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/companies/sign-in`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CompanySignInInputToJSON(requestParameters["companySignInInput"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CompanySignInOkResponseFromJSON(jsonValue),
    );
  }

  /**
   * Company Sign In
   */
  async postCompanySignIn(
    requestParameters: PostCompanySignInRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompanySignInOkResponse> {
    const response = await this.postCompanySignInRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
