/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { PlanStoreInput, PlanStoreResponse } from "../models/index";
import {
  PlanStoreInputFromJSON,
  PlanStoreInputToJSON,
  PlanStoreResponseFromJSON,
  PlanStoreResponseToJSON,
} from "../models/index";

export interface PostPlanRequest {
  planStoreInput: PlanStoreInput;
}

/**
 *
 */
export class PlansApi extends runtime.BaseAPI {
  /**
   * Create Plan
   */
  async postPlanRaw(
    requestParameters: PostPlanRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlanStoreResponse>> {
    if (requestParameters["planStoreInput"] == null) {
      throw new runtime.RequiredError(
        "planStoreInput",
        'Required parameter "planStoreInput" was null or undefined when calling postPlan().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/plans`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: PlanStoreInputToJSON(requestParameters["planStoreInput"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PlanStoreResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create Plan
   */
  async postPlan(
    requestParameters: PostPlanRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlanStoreResponse> {
    const response = await this.postPlanRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
