openapi: 3.1.0
info:
  title: companies
  version: '1.0'
  summary: ''
  description: companies APIs
servers:
  - url: 'http://localhost:8080'
paths:
  /companies/validateSignUp:
    post:
      summary: Validate SignUp
      responses:
        '200':
          $ref: '#/components/responses/SignUpResponse'
        '400':
          $ref: '#/components/responses/SignUpResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-auth-validate_sign_up
      requestBody:
        $ref: '#/components/requestBodies/SignUpInput'
      description: validate sign up
      tags:
        - companies
  /companies/signUp:
    post:
      summary: SignUp
      responses:
        '200':
          $ref: '#/components/responses/SignUpResponse'
        '400':
          $ref: '#/components/responses/SignUpResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-auth-sign_up
      requestBody:
        $ref: '#/components/requestBodies/SignUpInput'
      tags:
        - companies
components:
  schemas:
    SignUpValidationError:
      title: SignUpValidationError
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        finalTaxReturn:
          type: array
          items:
            type: string
  requestBodies:
    SignUpInput:
      content:
        multipart/form-data:
          schema:
            type: object
            required:
              - name
              - email
              - password
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
              finalTaxReturn:
                type: string
                format: binary
      description: SignUp Iuput
  responses:
    SignUpResponse:
      description: ''
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - errors
            properties:
              code:
                type: integer
                format: int64
              errors:
                type: object
                $ref: '#/components/schemas/SignUpValidationError'
    InternalServerErrorResponse:
      description: Internal Server Error Response
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                format: int64
              message:
                type: string
tags:
  - name: companies
    description: companies endpoint
