coverage:
  round: down
  range: 60...90
  precision: 2
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 50%

ignore:
  - 'api-server/api'
  - 'api-server/cmd'
  - 'api-server/database'
  - 'api-server/models'
  - 'api-server/test'
