coverage:
  round: down
  range: 60...90
  precision: 2
  status:
    project:
      registration:
        paths:
          - api_server/registration/**
        threshold: 0%
      business:
        paths:
          - api_server/business/**
        threshold: 0%
    patch:
      registration:
        paths:
          - api_server/registration/**
        target: 60%
      business:
        paths:
          - api_server/business/**
        target: 60%
