coverage:
  round: down
  range: 60...90
  precision: 2
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 60%

ignore:
  - 'api_server/business/api'
  - 'api_server/business/models'
  - 'api_server/business/test'
  - 'api_server/business/main.go'
  - 'api-server/api'
  - 'api-server/cmd'
  - 'api-server/database'
  - 'api-server/models'
