coverage:
  round: down
  range: 60...90
  precision: 2
  status:
    project:
      default:
        threshold: 0%
    patch:
      default:
        target: 60%

ignore:
  - 'api_server/business/api'
  - 'api_server/business/models'
  - 'api_server/business/test'
  - 'api_server/business/main.go'
  - 'api_server/registration/api'
  - 'api_server/registration/models'
  - 'api_server/registration/test'
  - 'api_server/registration/main.go'
