substitutions:
  _REGION: "asia-northeast1"
  _REGISTRATION_SERVIVE: "registration-front"
  _BUSINESS_SERVIVE: "business-front"
steps:
  # Registration Frontコンテナのビルド・プッシュ
  - name: "gcr.io/cloud-builders/docker"
    id: "build_registration_front"
    waitFor: ["-"]
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/${PROJECT_ID}/${_REGISTRATION_SERVIVE}/latest",
        "-f",
        "apps/registration/Dockerfile.deploy",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "push_registration_front_image"
    waitFor: ["build_registration_front"]
    args: ["push", "$_REGION-docker.pkg.dev/${PROJECT_ID}/${_REGISTRATION_SERVIVE}/latest"]

  # Cloud Run へデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    id: "deploy_registration_front"
    waitFor: ["push_registration_front_image"]
    args:
      - -c
      - |
        gcloud run deploy ${_REGISTRATION_SERVIVE} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRATION_SERVIVE}/latest \
          --project ${PROJECT_ID} \
          --platform managed \
          --region ${_REGION} \
          --service-account=storage-writer@it-support-453908.iam.gserviceaccount.com \
          --update-env-vars="REGISTRATION_API_ENDPOINT_URI=$$REGISTRATION_API_ENDPOINT_URI,TZ=$$TZ"
    secretEnv: ["REGISTRATION_API_ENDPOINT_URI", "TZ"]

  # Business Frontコンテナのビルド・プッシュ
  - name: "gcr.io/cloud-builders/docker"
    id: "build_business_front"
    waitFor: ["-"]
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/${PROJECT_ID}/${_BUSINESS_SERVIVE}/latest",
        "-f",
        "apps/business/Dockerfile.deploy",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "push_business_front_image"
    waitFor: ["build_business_front"]
    args: ["push", "$_REGION-docker.pkg.dev/${PROJECT_ID}/${_BUSINESS_SERVIVE}/latest"]

  # Cloud Run へデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    id: "deploy_business_front"
    waitFor: ["push_business_front_image"]
    args:
      - -c
      - |
        gcloud run deploy ${_BUSINESS_SERVIVE} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_BUSINESS_SERVIVE}/latest \
          --project ${PROJECT_ID} \
          --platform managed \
          --region ${_REGION} \
          --service-account=storage-writer@it-support-453908.iam.gserviceaccount.com \
          --update-env-vars="BUSINESS_API_ENDPOINT_URI=$$BUSINESS_API_ENDPOINT_URI,TZ=$$TZ"
    secretEnv: ["BUSINESS_API_ENDPOINT_URI", "TZ"]
availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/REGISTRATION_API_ENDPOINT_URI/versions/1"
      env: REGISTRATION_API_ENDPOINT_URI
    - versionName: "projects/${PROJECT_ID}/secrets/BUSINESS_API_ENDPOINT_URI/versions/1"
      env: BUSINESS_API_ENDPOINT_URI
    - versionName: "projects/${PROJECT_ID}/secrets/TZ/versions/1"
      env: TZ
