/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompanySignInOkResponse
 */
export interface CompanySignInOkResponse {
  /**
   *
   * @type {string}
   * @memberof CompanySignInOkResponse
   */
  token: string;
}

/**
 * Check if a given object implements the CompanySignInOkResponse interface.
 */
export function instanceOfCompanySignInOkResponse(value: object): value is CompanySignInOkResponse {
  if (!("token" in value) || value["token"] === undefined) return false;
  return true;
}

export function CompanySignInOkResponseFromJSON(json: any): CompanySignInOkResponse {
  return CompanySignInOkResponseFromJSONTyped(json, false);
}

export function CompanySignInOkResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanySignInOkResponse {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"],
  };
}

export function CompanySignInOkResponseToJSON(json: any): CompanySignInOkResponse {
  return CompanySignInOkResponseToJSONTyped(json, false);
}

export function CompanySignInOkResponseToJSONTyped(
  value?: CompanySignInOkResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
  };
}
