/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompanySignInBadRequestResponse
 */
export interface CompanySignInBadRequestResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof CompanySignInBadRequestResponse
   */
  errors: Array<string>;
}

/**
 * Check if a given object implements the CompanySignInBadRequestResponse interface.
 */
export function instanceOfCompanySignInBadRequestResponse(
  value: object,
): value is CompanySignInBadRequestResponse {
  if (!("errors" in value) || value["errors"] === undefined) return false;
  return true;
}

export function CompanySignInBadRequestResponseFromJSON(
  json: any,
): CompanySignInBadRequestResponse {
  return CompanySignInBadRequestResponseFromJSONTyped(json, false);
}

export function CompanySignInBadRequestResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanySignInBadRequestResponse {
  if (json == null) {
    return json;
  }
  return {
    errors: json["errors"],
  };
}

export function CompanySignInBadRequestResponseToJSON(json: any): CompanySignInBadRequestResponse {
  return CompanySignInBadRequestResponseToJSONTyped(json, false);
}

export function CompanySignInBadRequestResponseToJSONTyped(
  value?: CompanySignInBadRequestResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors: value["errors"],
  };
}
