/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompanySignInInput
 */
export interface CompanySignInInput {
  /**
   *
   * @type {string}
   * @memberof CompanySignInInput
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof CompanySignInInput
   */
  password: string;
}

/**
 * Check if a given object implements the CompanySignInInput interface.
 */
export function instanceOfCompanySignInInput(value: object): value is CompanySignInInput {
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  return true;
}

export function CompanySignInInputFromJSON(json: any): CompanySignInInput {
  return CompanySignInInputFromJSONTyped(json, false);
}

export function CompanySignInInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanySignInInput {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
  };
}

export function CompanySignInInputToJSON(json: any): CompanySignInInput {
  return CompanySignInInputToJSONTyped(json, false);
}

export function CompanySignInInputToJSONTyped(
  value?: CompanySignInInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
  };
}
