/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CsrfResponse
 */
export interface CsrfResponse {
  /**
   *
   * @type {string}
   * @memberof CsrfResponse
   */
  csrfToken: string;
}

/**
 * Check if a given object implements the CsrfResponse interface.
 */
export function instanceOfCsrfResponse(value: object): value is CsrfResponse {
  if (!("csrfToken" in value) || value["csrfToken"] === undefined) return false;
  return true;
}

export function CsrfResponseFromJSON(json: any): CsrfResponse {
  return CsrfResponseFromJSONTyped(json, false);
}

export function CsrfResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsrfResponse {
  if (json == null) {
    return json;
  }
  return {
    csrfToken: json["csrfToken"],
  };
}

export function CsrfResponseToJSON(json: any): CsrfResponse {
  return CsrfResponseToJSONTyped(json, false);
}

export function CsrfResponseToJSONTyped(
  value?: CsrfResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    csrfToken: value["csrfToken"],
  };
}
