/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlanStep
 */
export interface PlanStep {
  /**
   *
   * @type {number}
   * @memberof PlanStep
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof PlanStep
   */
  planId: number;
  /**
   *
   * @type {string}
   * @memberof PlanStep
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PlanStep
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof PlanStep
   */
  duration: number;
}

/**
 * Check if a given object implements the PlanStep interface.
 */
export function instanceOfPlanStep(value: object): value is PlanStep {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("planId" in value) || value["planId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("duration" in value) || value["duration"] === undefined) return false;
  return true;
}

export function PlanStepFromJSON(json: any): PlanStep {
  return PlanStepFromJSONTyped(json, false);
}

export function PlanStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanStep {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    planId: json["planId"],
    title: json["title"],
    description: json["description"],
    duration: json["duration"],
  };
}

export function PlanStepToJSON(json: any): PlanStep {
  return PlanStepToJSONTyped(json, false);
}

export function PlanStepToJSONTyped(
  value?: PlanStep | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    planId: value["planId"],
    title: value["title"],
    description: value["description"],
    duration: value["duration"],
  };
}
