/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlanValidationError
 */
export interface PlanValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof PlanValidationError
   */
  title?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanValidationError
   */
  description?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanValidationError
   */
  startDate?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanValidationError
   */
  endDate?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanValidationError
   */
  unitPrice?: Array<string>;
}

/**
 * Check if a given object implements the PlanValidationError interface.
 */
export function instanceOfPlanValidationError(value: object): value is PlanValidationError {
  return true;
}

export function PlanValidationErrorFromJSON(json: any): PlanValidationError {
  return PlanValidationErrorFromJSONTyped(json, false);
}

export function PlanValidationErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanValidationError {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"] == null ? undefined : json["title"],
    description: json["description"] == null ? undefined : json["description"],
    startDate: json["startDate"] == null ? undefined : json["startDate"],
    endDate: json["endDate"] == null ? undefined : json["endDate"],
    unitPrice: json["unitPrice"] == null ? undefined : json["unitPrice"],
  };
}

export function PlanValidationErrorToJSON(json: any): PlanValidationError {
  return PlanValidationErrorToJSONTyped(json, false);
}

export function PlanValidationErrorToJSONTyped(
  value?: PlanValidationError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    description: value["description"],
    startDate: value["startDate"],
    endDate: value["endDate"],
    unitPrice: value["unitPrice"],
  };
}
