/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlanStoreInput
 */
export interface PlanStoreInput {
  /**
   *
   * @type {number}
   * @memberof PlanStoreInput
   */
  projectId: number;
  /**
   *
   * @type {string}
   * @memberof PlanStoreInput
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PlanStoreInput
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof PlanStoreInput
   */
  startDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof PlanStoreInput
   */
  endDate?: Date;
  /**
   *
   * @type {number}
   * @memberof PlanStoreInput
   */
  unitPrice: number;
}

/**
 * Check if a given object implements the PlanStoreInput interface.
 */
export function instanceOfPlanStoreInput(value: object): value is PlanStoreInput {
  if (!("projectId" in value) || value["projectId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("unitPrice" in value) || value["unitPrice"] === undefined) return false;
  return true;
}

export function PlanStoreInputFromJSON(json: any): PlanStoreInput {
  return PlanStoreInputFromJSONTyped(json, false);
}

export function PlanStoreInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanStoreInput {
  if (json == null) {
    return json;
  }
  return {
    projectId: json["projectId"],
    title: json["title"],
    description: json["description"],
    startDate: json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    unitPrice: json["unitPrice"],
  };
}

export function PlanStoreInputToJSON(json: any): PlanStoreInput {
  return PlanStoreInputToJSONTyped(json, false);
}

export function PlanStoreInputToJSONTyped(
  value?: PlanStoreInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    projectId: value["projectId"],
    title: value["title"],
    description: value["description"],
    startDate:
      value["startDate"] == null ? undefined : value["startDate"].toISOString().substring(0, 10),
    endDate: value["endDate"] == null ? undefined : value["endDate"].toISOString().substring(0, 10),
    unitPrice: value["unitPrice"],
  };
}
