/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlanStepInput
 */
export interface PlanStepInput {
  /**
   *
   * @type {number}
   * @memberof PlanStepInput
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof PlanStepInput
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PlanStepInput
   */
  description: string;
  /**
   *
   * @type {number}
   * @memberof PlanStepInput
   */
  duration: number;
  /**
   *
   * @type {boolean}
   * @memberof PlanStepInput
   */
  deleted?: boolean;
}

/**
 * Check if a given object implements the PlanStepInput interface.
 */
export function instanceOfPlanStepInput(value: object): value is PlanStepInput {
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("duration" in value) || value["duration"] === undefined) return false;
  return true;
}

export function PlanStepInputFromJSON(json: any): PlanStepInput {
  return PlanStepInputFromJSONTyped(json, false);
}

export function PlanStepInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanStepInput {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    title: json["title"],
    description: json["description"],
    duration: json["duration"],
    deleted: json["deleted"] == null ? undefined : json["deleted"],
  };
}

export function PlanStepInputToJSON(json: any): PlanStepInput {
  return PlanStepInputToJSONTyped(json, false);
}

export function PlanStepInputToJSONTyped(
  value?: PlanStepInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    title: value["title"],
    description: value["description"],
    duration: value["duration"],
    deleted: value["deleted"],
  };
}
