/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PlanStepValidationError
 */
export interface PlanStepValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof PlanStepValidationError
   */
  title?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanStepValidationError
   */
  description?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanStepValidationError
   */
  duration?: Array<string>;
}

/**
 * Check if a given object implements the PlanStepValidationError interface.
 */
export function instanceOfPlanStepValidationError(value: object): value is PlanStepValidationError {
  return true;
}

export function PlanStepValidationErrorFromJSON(json: any): PlanStepValidationError {
  return PlanStepValidationErrorFromJSONTyped(json, false);
}

export function PlanStepValidationErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanStepValidationError {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"] == null ? undefined : json["title"],
    description: json["description"] == null ? undefined : json["description"],
    duration: json["duration"] == null ? undefined : json["duration"],
  };
}

export function PlanStepValidationErrorToJSON(json: any): PlanStepValidationError {
  return PlanStepValidationErrorToJSONTyped(json, false);
}

export function PlanStepValidationErrorToJSONTyped(
  value?: PlanStepValidationError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    description: value["description"],
    duration: value["duration"],
  };
}
