/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Plan
 */
export interface Plan {
  /**
   *
   * @type {number}
   * @memberof Plan
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof Plan
   */
  projectId: number;
  /**
   *
   * @type {string}
   * @memberof Plan
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Plan
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof Plan
   */
  startDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof Plan
   */
  endDate?: Date;
  /**
   *
   * @type {number}
   * @memberof Plan
   */
  unitPrice: number;
  /**
   *
   * @type {Date}
   * @memberof Plan
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the Plan interface.
 */
export function instanceOfPlan(value: object): value is Plan {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("projectId" in value) || value["projectId"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("unitPrice" in value) || value["unitPrice"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  return true;
}

export function PlanFromJSON(json: any): Plan {
  return PlanFromJSONTyped(json, false);
}

export function PlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plan {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    projectId: json["projectId"],
    title: json["title"],
    description: json["description"],
    startDate: json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    unitPrice: json["unitPrice"],
    createdAt: new Date(json["createdAt"]),
  };
}

export function PlanToJSON(json: any): Plan {
  return PlanToJSONTyped(json, false);
}

export function PlanToJSONTyped(value?: Plan | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    projectId: value["projectId"],
    title: value["title"],
    description: value["description"],
    startDate:
      value["startDate"] == null ? undefined : value["startDate"].toISOString().substring(0, 10),
    endDate: value["endDate"] == null ? undefined : value["endDate"].toISOString().substring(0, 10),
    unitPrice: value["unitPrice"],
    createdAt: value["createdAt"].toISOString(),
  };
}
