/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlanStepValidationError } from "./PlanStepValidationError";
import {
  PlanStepValidationErrorFromJSON,
  PlanStepValidationErrorFromJSONTyped,
  PlanStepValidationErrorToJSON,
  PlanStepValidationErrorToJSONTyped,
} from "./PlanStepValidationError";

/**
 *
 * @export
 * @interface PlanWithStepsValidationError
 */
export interface PlanWithStepsValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof PlanWithStepsValidationError
   */
  title?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanWithStepsValidationError
   */
  description?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanWithStepsValidationError
   */
  startDate?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanWithStepsValidationError
   */
  endDate?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanWithStepsValidationError
   */
  unitPrice?: Array<string>;
  /**
   *
   * @type {Array<PlanStepValidationError>}
   * @memberof PlanWithStepsValidationError
   */
  planSteps?: Array<PlanStepValidationError>;
}

/**
 * Check if a given object implements the PlanWithStepsValidationError interface.
 */
export function instanceOfPlanWithStepsValidationError(
  value: object,
): value is PlanWithStepsValidationError {
  return true;
}

export function PlanWithStepsValidationErrorFromJSON(json: any): PlanWithStepsValidationError {
  return PlanWithStepsValidationErrorFromJSONTyped(json, false);
}

export function PlanWithStepsValidationErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanWithStepsValidationError {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"] == null ? undefined : json["title"],
    description: json["description"] == null ? undefined : json["description"],
    startDate: json["startDate"] == null ? undefined : json["startDate"],
    endDate: json["endDate"] == null ? undefined : json["endDate"],
    unitPrice: json["unitPrice"] == null ? undefined : json["unitPrice"],
    planSteps:
      json["planSteps"] == null
        ? undefined
        : (json["planSteps"] as Array<any>).map(PlanStepValidationErrorFromJSON),
  };
}

export function PlanWithStepsValidationErrorToJSON(json: any): PlanWithStepsValidationError {
  return PlanWithStepsValidationErrorToJSONTyped(json, false);
}

export function PlanWithStepsValidationErrorToJSONTyped(
  value?: PlanWithStepsValidationError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    description: value["description"],
    startDate: value["startDate"],
    endDate: value["endDate"],
    unitPrice: value["unitPrice"],
    planSteps:
      value["planSteps"] == null
        ? undefined
        : (value["planSteps"] as Array<any>).map(PlanStepValidationErrorToJSON),
  };
}
