/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlanStepInput } from "./PlanStepInput";
import {
  PlanStepInputFromJSON,
  PlanStepInputFromJSONTyped,
  PlanStepInputToJSON,
  PlanStepInputToJSONTyped,
} from "./PlanStepInput";

/**
 *
 * @export
 * @interface PlanStoreWithStepsInput
 */
export interface PlanStoreWithStepsInput {
  /**
   *
   * @type {string}
   * @memberof PlanStoreWithStepsInput
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PlanStoreWithStepsInput
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof PlanStoreWithStepsInput
   */
  startDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof PlanStoreWithStepsInput
   */
  endDate?: Date;
  /**
   *
   * @type {number}
   * @memberof PlanStoreWithStepsInput
   */
  unitPrice: number;
  /**
   *
   * @type {Array<PlanStepInput>}
   * @memberof PlanStoreWithStepsInput
   */
  planSteps?: Array<PlanStepInput>;
}

/**
 * Check if a given object implements the PlanStoreWithStepsInput interface.
 */
export function instanceOfPlanStoreWithStepsInput(value: object): value is PlanStoreWithStepsInput {
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined) return false;
  if (!("unitPrice" in value) || value["unitPrice"] === undefined) return false;
  return true;
}

export function PlanStoreWithStepsInputFromJSON(json: any): PlanStoreWithStepsInput {
  return PlanStoreWithStepsInputFromJSONTyped(json, false);
}

export function PlanStoreWithStepsInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanStoreWithStepsInput {
  if (json == null) {
    return json;
  }
  return {
    title: json["title"],
    description: json["description"],
    startDate: json["startDate"] == null ? undefined : new Date(json["startDate"]),
    endDate: json["endDate"] == null ? undefined : new Date(json["endDate"]),
    unitPrice: json["unitPrice"],
    planSteps:
      json["planSteps"] == null
        ? undefined
        : (json["planSteps"] as Array<any>).map(PlanStepInputFromJSON),
  };
}

export function PlanStoreWithStepsInputToJSON(json: any): PlanStoreWithStepsInput {
  return PlanStoreWithStepsInputToJSONTyped(json, false);
}

export function PlanStoreWithStepsInputToJSONTyped(
  value?: PlanStoreWithStepsInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value["title"],
    description: value["description"],
    startDate:
      value["startDate"] == null ? undefined : value["startDate"].toISOString().substring(0, 10),
    endDate: value["endDate"] == null ? undefined : value["endDate"].toISOString().substring(0, 10),
    unitPrice: value["unitPrice"],
    planSteps:
      value["planSteps"] == null
        ? undefined
        : (value["planSteps"] as Array<any>).map(PlanStepInputToJSON),
  };
}
