/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Project } from "./Project";
import {
  ProjectFromJSON,
  ProjectFromJSONTyped,
  ProjectToJSON,
  ProjectToJSONTyped,
} from "./Project";

/**
 *
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
  /**
   *
   * @type {Project}
   * @memberof ProjectResponse
   */
  project: Project;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
  if (!("project" in value) || value["project"] === undefined) return false;
  return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
  return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectResponse {
  if (json == null) {
    return json;
  }
  return {
    project: ProjectFromJSON(json["project"]),
  };
}

export function ProjectResponseToJSON(json: any): ProjectResponse {
  return ProjectResponseToJSONTyped(json, false);
}

export function ProjectResponseToJSONTyped(
  value?: ProjectResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project: ProjectToJSON(value["project"]),
  };
}
