/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SupporterSignInInput
 */
export interface SupporterSignInInput {
  /**
   *
   * @type {string}
   * @memberof SupporterSignInInput
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof SupporterSignInInput
   */
  password: string;
}

/**
 * Check if a given object implements the SupporterSignInInput interface.
 */
export function instanceOfSupporterSignInInput(value: object): value is SupporterSignInInput {
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  return true;
}

export function SupporterSignInInputFromJSON(json: any): SupporterSignInInput {
  return SupporterSignInInputFromJSONTyped(json, false);
}

export function SupporterSignInInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SupporterSignInInput {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
  };
}

export function SupporterSignInInputToJSON(json: any): SupporterSignInInput {
  return SupporterSignInInputToJSONTyped(json, false);
}

export function SupporterSignInInputToJSONTyped(
  value?: SupporterSignInInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
  };
}
