/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SupporterSignInOkResponse
 */
export interface SupporterSignInOkResponse {
  /**
   *
   * @type {string}
   * @memberof SupporterSignInOkResponse
   */
  token: string;
}

/**
 * Check if a given object implements the SupporterSignInOkResponse interface.
 */
export function instanceOfSupporterSignInOkResponse(
  value: object,
): value is SupporterSignInOkResponse {
  if (!("token" in value) || value["token"] === undefined) return false;
  return true;
}

export function SupporterSignInOkResponseFromJSON(json: any): SupporterSignInOkResponse {
  return SupporterSignInOkResponseFromJSONTyped(json, false);
}

export function SupporterSignInOkResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SupporterSignInOkResponse {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"],
  };
}

export function SupporterSignInOkResponseToJSON(json: any): SupporterSignInOkResponse {
  return SupporterSignInOkResponseToJSONTyped(json, false);
}

export function SupporterSignInOkResponseToJSONTyped(
  value?: SupporterSignInOkResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
  };
}
