/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SupporterSignInBadRequestResponse
 */
export interface SupporterSignInBadRequestResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignInBadRequestResponse
   */
  errors: Array<string>;
}

/**
 * Check if a given object implements the SupporterSignInBadRequestResponse interface.
 */
export function instanceOfSupporterSignInBadRequestResponse(
  value: object,
): value is SupporterSignInBadRequestResponse {
  if (!("errors" in value) || value["errors"] === undefined) return false;
  return true;
}

export function SupporterSignInBadRequestResponseFromJSON(
  json: any,
): SupporterSignInBadRequestResponse {
  return SupporterSignInBadRequestResponseFromJSONTyped(json, false);
}

export function SupporterSignInBadRequestResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SupporterSignInBadRequestResponse {
  if (json == null) {
    return json;
  }
  return {
    errors: json["errors"],
  };
}

export function SupporterSignInBadRequestResponseToJSON(
  json: any,
): SupporterSignInBadRequestResponse {
  return SupporterSignInBadRequestResponseToJSONTyped(json, false);
}

export function SupporterSignInBadRequestResponseToJSONTyped(
  value?: SupporterSignInBadRequestResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors: value["errors"],
  };
}
