/* tslint:disable */
/* eslint-disable */
/**
 * Business Service
 * business APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ToProject } from "./ToProject";
import {
  ToProjectFromJSON,
  ToProjectFromJSONTyped,
  ToProjectToJSON,
  ToProjectToJSONTyped,
} from "./ToProject";

/**
 *
 * @export
 * @interface ToProjectResponse
 */
export interface ToProjectResponse {
  /**
   *
   * @type {ToProject}
   * @memberof ToProjectResponse
   */
  project: ToProject;
}

/**
 * Check if a given object implements the ToProjectResponse interface.
 */
export function instanceOfToProjectResponse(value: object): value is ToProjectResponse {
  if (!("project" in value) || value["project"] === undefined) return false;
  return true;
}

export function ToProjectResponseFromJSON(json: any): ToProjectResponse {
  return ToProjectResponseFromJSONTyped(json, false);
}

export function ToProjectResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ToProjectResponse {
  if (json == null) {
    return json;
  }
  return {
    project: ToProjectFromJSON(json["project"]),
  };
}

export function ToProjectResponseToJSON(json: any): ToProjectResponse {
  return ToProjectResponseToJSONTyped(json, false);
}

export function ToProjectResponseToJSONTyped(
  value?: ToProjectResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project: ToProjectToJSON(value["project"]),
  };
}
