development:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DBNAME}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true&loc=Local
  dir: ddl

test:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DBNAME}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true&loc=Local
  dir: ddl

deploy:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DBNAME}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true&loc=Local&tls=skip-verify
  dir: /app/ddl
