substitutions:
  _REGION: 'asia-northeast1'
  _SERVIVE: 'registration-api'
steps:
  # Registration APIコンテナのビルド・プッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/${PROJECT_ID}/${_SERVIVE}/latest',
        '-f',
        'Dockerfile.deploy',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/${PROJECT_ID}/${_SERVIVE}/latest']

  # Cloud Run へデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy ${_SERVIVE} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVIVE}/latest \
          --project ${PROJECT_ID} \
          --platform managed \
          --region ${_REGION} \
          --service-account=storage-writer@it-support-453908.iam.gserviceaccount.com \
          --update-env-vars="MYSQL_DBNAME=$$MYSQL_DBNAME,MYSQL_USER=$$MYSQL_USER,MYSQL_PASS=$$MYSQL_PASS,MYSQL_HOST=$$MYSQL_HOST,MYSQL_PORT=$$MYSQL_PORT,SERVER_PORT=$$SERVER_PORT,STORAGE_BUCKET_NAME=$$STORAGE_BUCKET_NAME,JWT_TOKEN_KEY=$$JWT_TOKEN_KEY,REGISTRATION_CLIENT_ORIGIN=$$REGISTRATION_CLIENT_ORIGIN,APP_ENV=$$APP_ENV" \
    secretEnv:
      [
        'MYSQL_DBNAME',
        'MYSQL_USER',
        'MYSQL_PASS',
        'MYSQL_HOST',
        'MYSQL_PORT',
        'SERVER_PORT',
        'STORAGE_BUCKET_NAME',
        'JWT_TOKEN_KEY',
        'REGISTRATION_CLIENT_ORIGIN',
        'APP_ENV',
      ]
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/MYSQL_DBNAME/versions/1'
      env: MYSQL_DBNAME
    - versionName: 'projects/${PROJECT_ID}/secrets/MYSQL_USER/versions/1'
      env: MYSQL_USER
    - versionName: 'projects/${PROJECT_ID}/secrets/MYSQL_PASS/versions/1'
      env: MYSQL_PASS
    - versionName: 'projects/${PROJECT_ID}/secrets/MYSQL_HOST/versions/1'
      env: MYSQL_HOST
    - versionName: 'projects/${PROJECT_ID}/secrets/MYSQL_PORT/versions/1'
      env: MYSQL_PORT
    - versionName: 'projects/${PROJECT_ID}/secrets/SERVER_PORT/versions/1'
      env: SERVER_PORT
    - versionName: 'projects/${PROJECT_ID}/secrets/STORAGE_BUCKET_NAME/versions/1'
      env: STORAGE_BUCKET_NAME
    - versionName: 'projects/${PROJECT_ID}/secrets/JWT_TOKEN_KEY/versions/1'
      env: JWT_TOKEN_KEY
    - versionName: 'projects/${PROJECT_ID}/secrets/REGISTRATION_CLIENT_ORIGIN/versions/1'
      env: REGISTRATION_CLIENT_ORIGIN
    - versionName: 'projects/${PROJECT_ID}/secrets/APP_ENV/versions/1'
      env: APP_ENV
