openapi: 3.1.0
info:
  title: companies
  version: '1.0'
  summary: ''
  description: companies APIs
servers:
  - url: 'http://localhost:8081'
paths:
  /companies/signIn:
    post:
      summary: SignIn
      responses:
        '200':
          $ref: '#/components/responses/SignInOkResponse'
        '400':
          $ref: '#/components/responses/SignInBadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-companies-sign_in
      requestBody:
        $ref: '#/components/requestBodies/SignInInput'
      tags:
        - companies
components:
  requestBodies:
    SignInInput:
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      description: SignIn  Input
  responses:
    SignInOkResponse:
      description: SignIn Response
      content:
        application/json:
          schema:
            type: object
      headers:
        Set-Cookie:
          schema:
            type: string
    SignInBadRequestResponse:
      description: SignIn BadRequest Response
      content:
        application/json:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                items:
                  type: string
    InternalServerErrorResponse:
      description: Internal Server Error Response
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                format: int64
              message:
                type: string
tags:
  - name: companies
    description: companies endpoint
