/* tslint:disable */
/* eslint-disable */
/**
 * Registration Service
 * registration APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanySignUpValidationError } from "./CompanySignUpValidationError";
import {
  CompanySignUpValidationErrorFromJSON,
  CompanySignUpValidationErrorFromJSONTyped,
  CompanySignUpValidationErrorToJSON,
  CompanySignUpValidationErrorToJSONTyped,
} from "./CompanySignUpValidationError";

/**
 *
 * @export
 * @interface CompanySignUpResponse
 */
export interface CompanySignUpResponse {
  /**
   *
   * @type {number}
   * @memberof CompanySignUpResponse
   */
  code: number;
  /**
   *
   * @type {CompanySignUpValidationError}
   * @memberof CompanySignUpResponse
   */
  errors: CompanySignUpValidationError;
}

/**
 * Check if a given object implements the CompanySignUpResponse interface.
 */
export function instanceOfCompanySignUpResponse(value: object): value is CompanySignUpResponse {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("errors" in value) || value["errors"] === undefined) return false;
  return true;
}

export function CompanySignUpResponseFromJSON(json: any): CompanySignUpResponse {
  return CompanySignUpResponseFromJSONTyped(json, false);
}

export function CompanySignUpResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanySignUpResponse {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    errors: CompanySignUpValidationErrorFromJSON(json["errors"]),
  };
}

export function CompanySignUpResponseToJSON(json: any): CompanySignUpResponse {
  return CompanySignUpResponseToJSONTyped(json, false);
}

export function CompanySignUpResponseToJSONTyped(
  value?: CompanySignUpResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    errors: CompanySignUpValidationErrorToJSON(value["errors"]),
  };
}
