/* tslint:disable */
/* eslint-disable */
/**
 * Registration Service
 * registration APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SupporterSignUpValidationError
 */
export interface SupporterSignUpValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  firstName?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  lastName?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  email?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  password?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  birthday?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  frontIdentification?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SupporterSignUpValidationError
   */
  backIdentification?: Array<string>;
}

/**
 * Check if a given object implements the SupporterSignUpValidationError interface.
 */
export function instanceOfSupporterSignUpValidationError(
  value: object,
): value is SupporterSignUpValidationError {
  return true;
}

export function SupporterSignUpValidationErrorFromJSON(json: any): SupporterSignUpValidationError {
  return SupporterSignUpValidationErrorFromJSONTyped(json, false);
}

export function SupporterSignUpValidationErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SupporterSignUpValidationError {
  if (json == null) {
    return json;
  }
  return {
    firstName: json["firstName"] == null ? undefined : json["firstName"],
    lastName: json["lastName"] == null ? undefined : json["lastName"],
    email: json["email"] == null ? undefined : json["email"],
    password: json["password"] == null ? undefined : json["password"],
    birthday: json["birthday"] == null ? undefined : json["birthday"],
    frontIdentification:
      json["frontIdentification"] == null ? undefined : json["frontIdentification"],
    backIdentification: json["backIdentification"] == null ? undefined : json["backIdentification"],
  };
}

export function SupporterSignUpValidationErrorToJSON(json: any): SupporterSignUpValidationError {
  return SupporterSignUpValidationErrorToJSONTyped(json, false);
}

export function SupporterSignUpValidationErrorToJSONTyped(
  value?: SupporterSignUpValidationError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    firstName: value["firstName"],
    lastName: value["lastName"],
    email: value["email"],
    password: value["password"],
    birthday: value["birthday"],
    frontIdentification: value["frontIdentification"],
    backIdentification: value["backIdentification"],
  };
}
