/* tslint:disable */
/* eslint-disable */
/**
 * Registration Service
 * registration APIs
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { CsrfResponse } from "../models/index";
import { CsrfResponseFromJSON, CsrfResponseToJSON } from "../models/index";

/**
 *
 */
export class CsrfApi extends runtime.BaseAPI {
  /**
   * Get Csrf
   */
  async getCsrfRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CsrfResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/csrf`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => CsrfResponseFromJSON(jsonValue));
  }

  /**
   * Get Csrf
   */
  async getCsrf(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CsrfResponse> {
    const response = await this.getCsrfRaw(initOverrides);
    return await response.value();
  }
}
