openapi: 3.1.0
info:
  title: Registration Service
  version: '1.0'
  description: registration APIs
tags:
  - name: companies
  - name: csrf
  - name: supporters
paths:
  /companies/sign-up:
    post:
      operationId: post-company-sign-up
      summary: Company Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - companies
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanySignUpInput'
  /companies/validate-sign-up:
    post:
      operationId: post-company-validate-sign-up
      summary: Company Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - companies
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanySignUpInput'
  /csrf:
    get:
      operationId: get-csrf
      summary: Get Csrf
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CsrfResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - csrf
  /supporters/sign-up:
    post:
      operationId: post-supporter-sign-up
      summary: Supporter Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - supporters
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SupporterSignUpInput'
  /supporters/validate-sign-up:
    post:
      operationId: post-supporter-validate-sign-up
      summary: Supporter Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - supporters
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SupporterSignUpInput'
components:
  schemas:
    CompanySignUpInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        finalTaxReturn:
          type: string
          format: binary
      required:
        - name
        - email
        - password
    CompanySignUpResponse:
      type: object
      required:
        - code
        - errors
      properties:
        code:
          type: integer
        errors:
          $ref: '#/components/schemas/CompanySignUpValidationError'
      title: Company SignUp Response
    CompanySignUpValidationError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        finalTaxReturn:
          type: array
          items:
            type: string
      title: Company SignUp Validation Error
    CsrfResponse:
      type: object
      required:
        - csrfToken
      properties:
        csrfToken:
          type: string
      title: CsrfResponse
    SupporterSignUpInput:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        birthday:
          type: string
          format: date
        frontIdentification:
          type: string
          format: binary
        backIdentification:
          type: string
          format: binary
      required:
        - firstName
        - lastName
        - email
        - password
    SupporterSignUpResponse:
      type: object
      required:
        - code
        - errors
      properties:
        code:
          type: integer
        errors:
          $ref: '#/components/schemas/SupporterSignUpValidationError'
      title: Supporter SignUp Response
    SupporterSignUpValidationError:
      type: object
      properties:
        firstName:
          type: array
          items:
            type: string
        lastName:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        birthday:
          type: array
          items:
            type: string
        frontIdentification:
          type: array
          items:
            type: string
        backIdentification:
          type: array
          items:
            type: string
      title: Supporter SignUp Validation Error
servers:
  - url: https://localhost:8080
    variables: {}
