openapi: 3.1.0
info:
  title: Registration Service
  version: '1.0'
  description: registration APIs
tags:
  - name: companies
paths:
  /companies/signUp:
    post:
      operationId: post-company-sign_up
      summary: Company Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - companies
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanySignUpInput'
      security:
        - ApiKeyAuth: []
  /companies/validateSignUp:
    post:
      operationId: post-company-validate_sign_up
      summary: Company Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
                  - message
      tags:
        - companies
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanySignUpInput'
      security:
        - ApiKeyAuth: []
components:
  schemas:
    Binary:
      type: string
      format: binary
    CompanySignUpInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        finalTaxReturn:
          $ref: '#/components/schemas/Binary'
      required:
        - name
        - email
        - password
    CompanySignUpResponse:
      type: object
      required:
        - code
        - errors
      properties:
        code:
          type: integer
        errors:
          $ref: '#/components/schemas/CompanySignUpValidationError'
      title: Company SignUp Response
    CompanySignUpValidationError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        finalTaxReturn:
          type: array
          items:
            type: string
      title: Company SignUp Validation Error
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: cookie
      name: token
servers:
  - url: https://localhost:8080
    variables: {}
