// Package registrationapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package registrationapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CompanySignUpInput defines model for CompanySignUpInput.
type CompanySignUpInput struct {
	Email          string              `json:"email"`
	FinalTaxReturn *openapi_types.File `json:"finalTaxReturn,omitempty"`
	Name           string              `json:"name"`
	Password       string              `json:"password"`
}

// CompanySignUpResponse defines model for CompanySignUpResponse.
type CompanySignUpResponse struct {
	Code   int                          `json:"code"`
	Errors CompanySignUpValidationError `json:"errors"`
}

// CompanySignUpValidationError defines model for CompanySignUpValidationError.
type CompanySignUpValidationError struct {
	Email          *[]string `json:"email,omitempty"`
	FinalTaxReturn *[]string `json:"finalTaxReturn,omitempty"`
	Name           *[]string `json:"name,omitempty"`
	Password       *[]string `json:"password,omitempty"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// SupporterSignUpInput defines model for SupporterSignUpInput.
type SupporterSignUpInput struct {
	BackIdentification  *openapi_types.File `json:"backIdentification,omitempty"`
	Birthday            *openapi_types.Date `json:"birthday,omitempty"`
	Email               string              `json:"email"`
	FirstName           string              `json:"firstName"`
	FrontIdentification *openapi_types.File `json:"frontIdentification,omitempty"`
	LastName            string              `json:"lastName"`
	Password            string              `json:"password"`
}

// SupporterSignUpResponse defines model for SupporterSignUpResponse.
type SupporterSignUpResponse struct {
	Code   int                            `json:"code"`
	Errors SupporterSignUpValidationError `json:"errors"`
}

// SupporterSignUpValidationError defines model for SupporterSignUpValidationError.
type SupporterSignUpValidationError struct {
	BackIdentification  *[]string `json:"backIdentification,omitempty"`
	Birthday            *[]string `json:"birthday,omitempty"`
	Email               *[]string `json:"email,omitempty"`
	FirstName           *[]string `json:"firstName,omitempty"`
	FrontIdentification *[]string `json:"frontIdentification,omitempty"`
	LastName            *[]string `json:"lastName,omitempty"`
	Password            *[]string `json:"password,omitempty"`
}

// PostCompanySignUpMultipartRequestBody defines body for PostCompanySignUp for multipart/form-data ContentType.
type PostCompanySignUpMultipartRequestBody = CompanySignUpInput

// PostCompanyValidateSignUpMultipartRequestBody defines body for PostCompanyValidateSignUp for multipart/form-data ContentType.
type PostCompanyValidateSignUpMultipartRequestBody = CompanySignUpInput

// PostSupporterSignUpMultipartRequestBody defines body for PostSupporterSignUp for multipart/form-data ContentType.
type PostSupporterSignUpMultipartRequestBody = SupporterSignUpInput

// PostSupporterValidateSignUpMultipartRequestBody defines body for PostSupporterValidateSignUp for multipart/form-data ContentType.
type PostSupporterValidateSignUpMultipartRequestBody = SupporterSignUpInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Company Sign Up
	// (POST /companies/sign-up)
	PostCompanySignUp(ctx echo.Context) error
	// Company Validate Sign Up
	// (POST /companies/validate-sign-up)
	PostCompanyValidateSignUp(ctx echo.Context) error
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Supporter Sign Up
	// (POST /supporters/sign-up)
	PostSupporterSignUp(ctx echo.Context) error
	// Supporter Validate Sign Up
	// (POST /supporters/validate-sign-up)
	PostSupporterValidateSignUp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostCompanySignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostCompanySignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCompanySignUp(ctx)
	return err
}

// PostCompanyValidateSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostCompanyValidateSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCompanyValidateSignUp(ctx)
	return err
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// PostSupporterSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostSupporterSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSupporterSignUp(ctx)
	return err
}

// PostSupporterValidateSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostSupporterValidateSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSupporterValidateSignUp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/companies/sign-up", wrapper.PostCompanySignUp)
	router.POST(baseURL+"/companies/validate-sign-up", wrapper.PostCompanyValidateSignUp)
	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.POST(baseURL+"/supporters/sign-up", wrapper.PostSupporterSignUp)
	router.POST(baseURL+"/supporters/validate-sign-up", wrapper.PostSupporterValidateSignUp)

}

type PostCompanySignUpRequestObject struct {
	Body *multipart.Reader
}

type PostCompanySignUpResponseObject interface {
	VisitPostCompanySignUpResponse(w http.ResponseWriter) error
}

type PostCompanySignUp200JSONResponse CompanySignUpResponse

func (response PostCompanySignUp200JSONResponse) VisitPostCompanySignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanySignUp400JSONResponse CompanySignUpResponse

func (response PostCompanySignUp400JSONResponse) VisitPostCompanySignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanySignUp500JSONResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PostCompanySignUp500JSONResponse) VisitPostCompanySignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanyValidateSignUpRequestObject struct {
	Body *multipart.Reader
}

type PostCompanyValidateSignUpResponseObject interface {
	VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error
}

type PostCompanyValidateSignUp200JSONResponse CompanySignUpResponse

func (response PostCompanyValidateSignUp200JSONResponse) VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanyValidateSignUp400JSONResponse CompanySignUpResponse

func (response PostCompanyValidateSignUp400JSONResponse) VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanyValidateSignUp500JSONResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PostCompanyValidateSignUp500JSONResponse) VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrfRequestObject struct {
}

type GetCsrfResponseObject interface {
	VisitGetCsrfResponse(w http.ResponseWriter) error
}

type GetCsrf200JSONResponse CsrfResponse

func (response GetCsrf200JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrf500JSONResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response GetCsrf500JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterSignUpRequestObject struct {
	Body *multipart.Reader
}

type PostSupporterSignUpResponseObject interface {
	VisitPostSupporterSignUpResponse(w http.ResponseWriter) error
}

type PostSupporterSignUp200JSONResponse SupporterSignUpResponse

func (response PostSupporterSignUp200JSONResponse) VisitPostSupporterSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterSignUp400JSONResponse SupporterSignUpResponse

func (response PostSupporterSignUp400JSONResponse) VisitPostSupporterSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterSignUp500JSONResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PostSupporterSignUp500JSONResponse) VisitPostSupporterSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterValidateSignUpRequestObject struct {
	Body *multipart.Reader
}

type PostSupporterValidateSignUpResponseObject interface {
	VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error
}

type PostSupporterValidateSignUp200JSONResponse SupporterSignUpResponse

func (response PostSupporterValidateSignUp200JSONResponse) VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterValidateSignUp400JSONResponse SupporterSignUpResponse

func (response PostSupporterValidateSignUp400JSONResponse) VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterValidateSignUp500JSONResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PostSupporterValidateSignUp500JSONResponse) VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Company Sign Up
	// (POST /companies/sign-up)
	PostCompanySignUp(ctx context.Context, request PostCompanySignUpRequestObject) (PostCompanySignUpResponseObject, error)
	// Company Validate Sign Up
	// (POST /companies/validate-sign-up)
	PostCompanyValidateSignUp(ctx context.Context, request PostCompanyValidateSignUpRequestObject) (PostCompanyValidateSignUpResponseObject, error)
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx context.Context, request GetCsrfRequestObject) (GetCsrfResponseObject, error)
	// Supporter Sign Up
	// (POST /supporters/sign-up)
	PostSupporterSignUp(ctx context.Context, request PostSupporterSignUpRequestObject) (PostSupporterSignUpResponseObject, error)
	// Supporter Validate Sign Up
	// (POST /supporters/validate-sign-up)
	PostSupporterValidateSignUp(ctx context.Context, request PostSupporterValidateSignUpRequestObject) (PostSupporterValidateSignUpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostCompanySignUp operation middleware
func (sh *strictHandler) PostCompanySignUp(ctx echo.Context) error {
	var request PostCompanySignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCompanySignUp(ctx.Request().Context(), request.(PostCompanySignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCompanySignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCompanySignUpResponseObject); ok {
		return validResponse.VisitPostCompanySignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostCompanyValidateSignUp operation middleware
func (sh *strictHandler) PostCompanyValidateSignUp(ctx echo.Context) error {
	var request PostCompanyValidateSignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCompanyValidateSignUp(ctx.Request().Context(), request.(PostCompanyValidateSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCompanyValidateSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCompanyValidateSignUpResponseObject); ok {
		return validResponse.VisitPostCompanyValidateSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCsrf operation middleware
func (sh *strictHandler) GetCsrf(ctx echo.Context) error {
	var request GetCsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCsrf(ctx.Request().Context(), request.(GetCsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCsrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCsrfResponseObject); ok {
		return validResponse.VisitGetCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostSupporterSignUp operation middleware
func (sh *strictHandler) PostSupporterSignUp(ctx echo.Context) error {
	var request PostSupporterSignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSupporterSignUp(ctx.Request().Context(), request.(PostSupporterSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSupporterSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostSupporterSignUpResponseObject); ok {
		return validResponse.VisitPostSupporterSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostSupporterValidateSignUp operation middleware
func (sh *strictHandler) PostSupporterValidateSignUp(ctx echo.Context) error {
	var request PostSupporterValidateSignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSupporterValidateSignUp(ctx.Request().Context(), request.(PostSupporterValidateSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSupporterValidateSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostSupporterValidateSignUpResponseObject); ok {
		return validResponse.VisitPostSupporterValidateSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/jNhD9KwLboxO7X8BCt7YoFrkUiyTtpfCBEUc2dyWSnRm5awT+7wVJRaJsxZED",
	"OEEL32yJ8/3e49iPorC1swYMk8gfBRVrqGX4+KutnTTbO70yf7gb4xr2Tx1aB8gawhmopa78B946ELkg",
	"Rm1WYjcTpTayupdfb4EbNP5IabGWLHLxoI3ErZgdGhlZw6g3J4n+sahGXu5mAuHvRiMokf8VXczaxBLD",
	"ZRfOPnyGgr3XQYW3QM4agsMiC6vSrLRhWAF6B4BoMZz5FqEUufhm3rdz3vZyPgjzp6y0kqyt+c0bH+Qf",
	"gnWefdaaKx+29ZJFN1mX7kt17Qd8foaaoabR9rcPJKLcjg93uu3TjKdbpMOfarV7tnF9P7LYkLEGEpZH",
	"8EBY3tsvYF5GY380nWTqfST6XeOcRQY8Sr0HWXy5UWBYl7oI9Uwk2YNGXiu5HRxXkmHs8DGCI/HvzxG2",
	"RGv4VelV8ojb6TrQp5e4nKgLewM4nzLsBXq1NnR+pqjDC0EnAm06fVO8Tbd6lSoliDzBbByq0x2kiH0z",
	"VTsY+cu65s21Ka0PpIAK1C4WKxBWmhij9c+fbkj0gW7Td3eAG114WG0AKRp/d73wmVoHRjotcvHDtX/k",
	"K+R1qCpAXxoNNCe9MleNCyizFGTNYy14v1EiF58s8eD+EpEDQPyLVdvIOsNggm3dVKydRJ57ZblSkmW/",
	"xZx0L0eV3Q0px9hAeBDZFIr5frHYS0I6V7XAmX+miJ5XZNBxNiQxHND9GrK2C9laUkZNUQAoUNe+9T++",
	"V0oEuAHMCttUKjOWs8YoQGJpVMZJyqqBjG2mzcaDNKOtYfk1pP7TialP1d8aiOQKJtzQUVOfzi9HWTOs",
	"/C5WDZ1GU1PX/jYb7hpZwC7LFcU4LQXE0psklNhE4sLVKdxo2Q4Xjlw48h/lyBOEp5CFsPRprmCEFR+B",
	"/UYtzonBdGM/GXr/s/l9BM7ahnfz8l/jqOhpL5l41+9to+dTstFfVW+sZc/9sHhXNTsxqYue7fFhuIkP",
	"haxnwyE9Trv3uyhvdfNf+HLhy5n5cmQDGBLH2weH/t2jaLASuVgzO8rn88oWslpb4vzD4sNC7Jadl8f2",
	"z8Zkn9jN+of+0kq+JyF3y92/AQAA//+RlC7vGRcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
