// Package registrationapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package registrationapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CompanySignUpInput defines model for CompanySignUpInput.
type CompanySignUpInput struct {
	Email          string              `json:"email"`
	FinalTaxReturn *openapi_types.File `json:"finalTaxReturn,omitempty"`
	Name           string              `json:"name"`
	Password       string              `json:"password"`
}

// CompanySignUpResponse defines model for CompanySignUpResponse.
type CompanySignUpResponse struct {
	Code   int                          `json:"code"`
	Errors CompanySignUpValidationError `json:"errors"`
}

// CompanySignUpValidationError defines model for CompanySignUpValidationError.
type CompanySignUpValidationError struct {
	Email          *[]string `json:"email,omitempty"`
	FinalTaxReturn *[]string `json:"finalTaxReturn,omitempty"`
	Name           *[]string `json:"name,omitempty"`
	Password       *[]string `json:"password,omitempty"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// SupporterSignUpInput defines model for SupporterSignUpInput.
type SupporterSignUpInput struct {
	BackIdentification  *openapi_types.File `json:"backIdentification,omitempty"`
	Birthday            *openapi_types.Date `json:"birthday,omitempty"`
	Email               string              `json:"email"`
	FirstName           string              `json:"firstName"`
	FrontIdentification *openapi_types.File `json:"frontIdentification,omitempty"`
	LastName            string              `json:"lastName"`
	Password            string              `json:"password"`
}

// SupporterSignUpResponse defines model for SupporterSignUpResponse.
type SupporterSignUpResponse struct {
	Code   int                            `json:"code"`
	Errors SupporterSignUpValidationError `json:"errors"`
}

// SupporterSignUpValidationError defines model for SupporterSignUpValidationError.
type SupporterSignUpValidationError struct {
	BackIdentification  *[]string `json:"backIdentification,omitempty"`
	Birthday            *[]string `json:"birthday,omitempty"`
	Email               *[]string `json:"email,omitempty"`
	FirstName           *[]string `json:"firstName,omitempty"`
	FrontIdentification *[]string `json:"frontIdentification,omitempty"`
	LastName            *[]string `json:"lastName,omitempty"`
	Password            *[]string `json:"password,omitempty"`
}

// PostCompanySignUpMultipartRequestBody defines body for PostCompanySignUp for multipart/form-data ContentType.
type PostCompanySignUpMultipartRequestBody = CompanySignUpInput

// PostCompanyValidateSignUpMultipartRequestBody defines body for PostCompanyValidateSignUp for multipart/form-data ContentType.
type PostCompanyValidateSignUpMultipartRequestBody = CompanySignUpInput

// PostSupporterSignUpMultipartRequestBody defines body for PostSupporterSignUp for multipart/form-data ContentType.
type PostSupporterSignUpMultipartRequestBody = SupporterSignUpInput

// PostSupporterValidateSignUpMultipartRequestBody defines body for PostSupporterValidateSignUp for multipart/form-data ContentType.
type PostSupporterValidateSignUpMultipartRequestBody = SupporterSignUpInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Company Sign Up
	// (POST /companies/sign-up)
	PostCompanySignUp(ctx echo.Context) error
	// Company Validate Sign Up
	// (POST /companies/validate-sign-up)
	PostCompanyValidateSignUp(ctx echo.Context) error
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Supporter Sign Up
	// (POST /supporters/sign-up)
	PostSupporterSignUp(ctx echo.Context) error
	// Supporter Validate Sign Up
	// (POST /supporters/validate-sign-up)
	PostSupporterValidateSignUp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostCompanySignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostCompanySignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCompanySignUp(ctx)
	return err
}

// PostCompanyValidateSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostCompanyValidateSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCompanyValidateSignUp(ctx)
	return err
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// PostSupporterSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostSupporterSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSupporterSignUp(ctx)
	return err
}

// PostSupporterValidateSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostSupporterValidateSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSupporterValidateSignUp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/companies/sign-up", wrapper.PostCompanySignUp)
	router.POST(baseURL+"/companies/validate-sign-up", wrapper.PostCompanyValidateSignUp)
	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.POST(baseURL+"/supporters/sign-up", wrapper.PostSupporterSignUp)
	router.POST(baseURL+"/supporters/validate-sign-up", wrapper.PostSupporterValidateSignUp)

}

type PostCompanySignUpRequestObject struct {
	Body *multipart.Reader
}

type PostCompanySignUpResponseObject interface {
	VisitPostCompanySignUpResponse(w http.ResponseWriter) error
}

type PostCompanySignUp200JSONResponse CompanySignUpResponse

func (response PostCompanySignUp200JSONResponse) VisitPostCompanySignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanySignUp400JSONResponse CompanySignUpResponse

func (response PostCompanySignUp400JSONResponse) VisitPostCompanySignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanySignUp500Response struct {
}

func (response PostCompanySignUp500Response) VisitPostCompanySignUpResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostCompanyValidateSignUpRequestObject struct {
	Body *multipart.Reader
}

type PostCompanyValidateSignUpResponseObject interface {
	VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error
}

type PostCompanyValidateSignUp200JSONResponse CompanySignUpResponse

func (response PostCompanyValidateSignUp200JSONResponse) VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanyValidateSignUp400JSONResponse CompanySignUpResponse

func (response PostCompanyValidateSignUp400JSONResponse) VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostCompanyValidateSignUp500Response struct {
}

func (response PostCompanyValidateSignUp500Response) VisitPostCompanyValidateSignUpResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetCsrfRequestObject struct {
}

type GetCsrfResponseObject interface {
	VisitGetCsrfResponse(w http.ResponseWriter) error
}

type GetCsrf200JSONResponse CsrfResponse

func (response GetCsrf200JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrf500Response struct {
}

func (response GetCsrf500Response) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostSupporterSignUpRequestObject struct {
	Body *multipart.Reader
}

type PostSupporterSignUpResponseObject interface {
	VisitPostSupporterSignUpResponse(w http.ResponseWriter) error
}

type PostSupporterSignUp200JSONResponse SupporterSignUpResponse

func (response PostSupporterSignUp200JSONResponse) VisitPostSupporterSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterSignUp400JSONResponse SupporterSignUpResponse

func (response PostSupporterSignUp400JSONResponse) VisitPostSupporterSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterSignUp500Response struct {
}

func (response PostSupporterSignUp500Response) VisitPostSupporterSignUpResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostSupporterValidateSignUpRequestObject struct {
	Body *multipart.Reader
}

type PostSupporterValidateSignUpResponseObject interface {
	VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error
}

type PostSupporterValidateSignUp200JSONResponse SupporterSignUpResponse

func (response PostSupporterValidateSignUp200JSONResponse) VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterValidateSignUp400JSONResponse SupporterSignUpResponse

func (response PostSupporterValidateSignUp400JSONResponse) VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostSupporterValidateSignUp500Response struct {
}

func (response PostSupporterValidateSignUp500Response) VisitPostSupporterValidateSignUpResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Company Sign Up
	// (POST /companies/sign-up)
	PostCompanySignUp(ctx context.Context, request PostCompanySignUpRequestObject) (PostCompanySignUpResponseObject, error)
	// Company Validate Sign Up
	// (POST /companies/validate-sign-up)
	PostCompanyValidateSignUp(ctx context.Context, request PostCompanyValidateSignUpRequestObject) (PostCompanyValidateSignUpResponseObject, error)
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx context.Context, request GetCsrfRequestObject) (GetCsrfResponseObject, error)
	// Supporter Sign Up
	// (POST /supporters/sign-up)
	PostSupporterSignUp(ctx context.Context, request PostSupporterSignUpRequestObject) (PostSupporterSignUpResponseObject, error)
	// Supporter Validate Sign Up
	// (POST /supporters/validate-sign-up)
	PostSupporterValidateSignUp(ctx context.Context, request PostSupporterValidateSignUpRequestObject) (PostSupporterValidateSignUpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostCompanySignUp operation middleware
func (sh *strictHandler) PostCompanySignUp(ctx echo.Context) error {
	var request PostCompanySignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCompanySignUp(ctx.Request().Context(), request.(PostCompanySignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCompanySignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCompanySignUpResponseObject); ok {
		return validResponse.VisitPostCompanySignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostCompanyValidateSignUp operation middleware
func (sh *strictHandler) PostCompanyValidateSignUp(ctx echo.Context) error {
	var request PostCompanyValidateSignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostCompanyValidateSignUp(ctx.Request().Context(), request.(PostCompanyValidateSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCompanyValidateSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostCompanyValidateSignUpResponseObject); ok {
		return validResponse.VisitPostCompanyValidateSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCsrf operation middleware
func (sh *strictHandler) GetCsrf(ctx echo.Context) error {
	var request GetCsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCsrf(ctx.Request().Context(), request.(GetCsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCsrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCsrfResponseObject); ok {
		return validResponse.VisitGetCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostSupporterSignUp operation middleware
func (sh *strictHandler) PostSupporterSignUp(ctx echo.Context) error {
	var request PostSupporterSignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSupporterSignUp(ctx.Request().Context(), request.(PostSupporterSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSupporterSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostSupporterSignUpResponseObject); ok {
		return validResponse.VisitPostSupporterSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostSupporterValidateSignUp operation middleware
func (sh *strictHandler) PostSupporterValidateSignUp(ctx echo.Context) error {
	var request PostSupporterValidateSignUpRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostSupporterValidateSignUp(ctx.Request().Context(), request.(PostSupporterValidateSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSupporterValidateSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostSupporterValidateSignUpResponseObject); ok {
		return validResponse.VisitPostSupporterValidateSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/jNhD9KwLboxO7X8BCt7YoFrkUiyTtpciBEUc2dyWSnRm5awT67wVJRaJs2ZED",
	"JMECucUU583XezNEHkRha2cNGCaRPwgqNlDL8OfvtnbS7G702vzlroxr2J86tA6QNYQ7UEtd+T9450Dk",
	"ghi1WYt2IUptZHUrv14DN2j8ldJiLVnk4l4biTuxODQysoZJNCeJ/rOoJj62C4Hwb6MRlMj/iRCLLrDE",
	"8K53Z+8/Q8EedZThNZCzhuAwycKqNCptGNaAHgAQLYY73yOUIhffLYdyLrtaLkdu/paVVpK1NX9444P4",
	"g7Me2UetufJuO5QswmR9uE/lte/weA81Q02T5e8OJKLcTTd3vu1jj+dbpM2fa9UeLdxQjywWZKqAhOUJ",
	"PhCWt/YLmKfZOFxNO5miT3i/aZyzyIAnpXcviy9XCgzrUhchn5kiu9fIGyV3o+tKMkxdPiVwJP7zmGBL",
	"tIafFV4lT8DOnwNDeAnkzLmw14CXmwx7jp49G3qcOdPhCacziTZfvinf5ls9ayoljDzDbJqq8wFSxr7a",
	"VDto+dNzzZtrU1rvSAEVqF1MViCsNTFG618/XZEYHF2n324At7rwtNoCUjT+4XLlI7UOjHRa5OKnS3/k",
	"M+RNyCpQXxoNtCS9NheNCyyzFMaa51pAv1IiF58s8Wh/iagBIP7Nql1UnWEwwbZuKtZOIi/9ZLlQkuXw",
	"ijlrL8cp244lx9hAOIhqCsn8uFrtBSGdqzriLD9TZM8zIug1G4IYN+h2A1lXhWwjKaOmKAAUqEtf+p/f",
	"KiQC3AJmhW0qlRnLWWMUILE0KuMkZNVAxjbTZutJmtHOsPwaQv8lhj6Gvomw0A9Baurar4vxMs8COViu",
	"KQ7HjmPizpsknNtGZcDFOeTr5ATvJHwn4TESPnJkDhsJS+9jDRO0+wjs34TiJZucvjnP7u25BfoInHUZ",
	"9QXxP2Mt6HF1zVwHew+Wl9Pi5MP7ldV47O35pno8M6jXV+T4NTSW4kC3Q/6dtxp6L6+1HN4J+e0T8sSS",
	"GDPT2wdA/+1BNFiJXGyYHeXLZWULWW0scf5h9WEl2rse5aH7j0qyctrFcOjHbvI7cdnetf8HAAD//+mG",
	"gvv+EwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
