openapi: 3.1.0
info:
  title: business
  version: '1.0'
  summary: ''
  description: business APIs
servers:
  - url: 'http://localhost:8081'
paths:
  /csrf:
    get:
      summary: Get Csrf
      responses:
        '200':
          $ref: '#/components/responses/CsrfResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: get-csrf
      security: []
      tags:
        - csrf
  /supporters/signIn:
    post:
      summary: Supporter SignIn
      responses:
        '200':
          $ref: '#/components/responses/SupporterSignInOkResponse'
        '400':
          $ref: '#/components/responses/SupporterSignInBadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-supporters-sign_in
      security: []
      requestBody:
        $ref: '#/components/requestBodies/SupporterSignInInput'
      tags:
        - supporters
  /companies/signIn:
    post:
      summary: SignIn
      responses:
        '200':
          $ref: '#/components/responses/CompanySignInOkResponse'
        '400':
          $ref: '#/components/responses/CompanySignInBadRequestResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-companies-sign_in
      security: []
      requestBody:
        $ref: '#/components/requestBodies/CompanySignInInput'
      tags:
        - companies
  /projects:
    get:
      summary: Project List
      tags:
        - projects
      responses:
        '200':
          $ref: '#/components/responses/ProjectsListResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: get-projects
      security:
        - businessAuthentication: []
      parameters:
        - schema:
            type: string
          in: query
          name: pageToken
    post:
      summary: Project Create
      tags:
        - projects
      responses:
        '200':
          $ref: '#/components/responses/ProjectStoreResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: post-projects
      security:
        - businessAuthentication: []
      requestBody:
        $ref: '#/components/requestBodies/ProjectStoreInput'
  '/projects/{id}':
    get:
      summary: Project Show
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      tags:
        - projects
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
        '404':
          $ref: '#/components/responses/NotFoundErrorResponse'
      operationId: get-projects-id
      security:
        - businessAuthentication: []
    put:
      summary: Project Update
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      tags:
        - projects
      responses:
        '200':
          $ref: '#/components/responses/ProjectStoreResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
      operationId: put-projects-id
      security:
        - businessAuthentication: []
      requestBody:
        $ref: '#/components/requestBodies/ProjectStoreInput'
components:
  schemas:
    Project:
      title: Project Model
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        min_budget:
          type: integer
        max_budget:
          type: integer
        isActive:
          type: boolean
        created_at:
          type: string
          format: date-time
      description: Project
    ProjectValidationError:
      title: ProjectValidationErrors
      type: object
      properties:
        title:
          type: array
          items:
            type: string
        description:
          type: array
          items:
            type: string
        startDate:
          type: array
          items:
            type: string
        endDate:
          type: array
          items:
            type: string
        minBudget:
          type: array
          items:
            type: string
        maxBudget:
          type: array
          items:
            type: string
        isActive:
          type: array
          items:
            type: string
  requestBodies:
    ProjectStoreInput:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              startDate:
                type: string
                format: date
              endDate:
                type: string
                format: date
              minBudget:
                type: integer
              maxBudget:
                type: integer
              isActive:
                type: boolean
      description: Project Store Inputs
    SupporterSignInInput:
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      description: Supporter SignIn  Input
    CompanySignInInput:
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      description: Company SignIn  Input
  responses:
    CsrfResponse:
      description: Csrf response
      content:
        application/json:
          schema:
            type: object
            required:
              - csrfToken
            properties:
              csrfToken:
                type: string
    SupporterSignInOkResponse:
      description: Supporter SignIn Response
      content:
        application/json:
          schema:
            type: object
      headers:
        Set-Cookie:
          schema:
            type: string
    SupporterSignInBadRequestResponse:
      description: Supporter SignIn BadRequest Response
      content:
        application/json:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                items:
                  type: string
    CompanySignInOkResponse:
      description: Company SignIn Response
      content:
        application/json:
          schema:
            type: object
      headers:
        Set-Cookie:
          schema:
            type: string
    CompanySignInBadRequestResponse:
      description: Company SignIn BadRequest Response
      content:
        application/json:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                items:
                  type: string
    ProjectStoreResponse:
      description: Project Store Response
      content:
        application/json:
          schema:
            type: object
            required:
              - project
              - errors
            properties:
              project:
                $ref: '#/components/schemas/Project'
              errors:
                $ref: '#/components/schemas/ProjectValidationError'
    ProjectsListResponse:
      description: Projects List Response
      content:
        application/json:
          schema:
            type: object
            required:
              - projects
              - nextPageToken
            properties:
              projects:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
              nextPageToken:
                type: string
    ProjectResponse:
      description: Project Response
      content:
        application/json:
          schema:
            type: object
            required:
              - project
            properties:
              project:
                $ref: '#/components/schemas/Project'
    NotFoundErrorResponse:
      description: Not Found Error Response
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
              message:
                type: string
    InternalServerErrorResponse:
      description: Internal Server Error Response
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
              message:
                type: string
  securitySchemes:
    businessAuthentication:
      name: token
      type: apiKey
      in: cookie
tags:
  - name: csrf
    description: csrf endpoint
  - name: supporters
    description: supporters endpoint
  - name: companies
    description: companies endpoint
